### Get user by id (replace <TOKEN> with the token from login)
GET http://localhost:8080/users/1
Accept: */*
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJSaWRlVG9nZXRoZXJBcHAiLCJzdWIiOiJqb2huLmRvZUBleGFtcGxlLmNvbSIsImlkIjoiMSIsInJvbGUiOiJEUklWRVIiLCJpYXQiOjE3NTYyMDUxMDQsImV4cCI6MTc1NjgwOTkwNH0.KWn-6dyTaBkR40XYvJK-3bB1-aaYl3ac-SnCNMLKMws

